import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:5175/');
  await page.getByRole('slider', { name: 'Уровень затемнения фона' }).fill('6');
  await page.getByText('РЕЖИМЫ').click();
  await page.getByText('ОБЫЧНЫЙ РЕЖИМ').click();
  await page.locator('body').press('ArrowLeft');
  await page.locator('body').press('ArrowLeft');
  await page.locator('body').press('ArrowLeft');
  await page.locator('body').press('ArrowLeft');
  await page.locator('body').press('ArrowLeft');
  await page.locator('body').press('ArrowLeft');
  await page.locator('body').press('ArrowLeft');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowLeft');
  await page.locator('body').press('ArrowLeft');а
  await page.locator('body').press('ArrowLeft');
  await page.getByRole('button', { name: 'ПАУЗА' }).click();
  await page.getByRole('button', { name: 'МУЗЫКА' }).click();
  await page.locator('div').filter({ hasText: /^0:002:59$/ }).getByRole('slider').fill('64');
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(2).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(3).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(1).click();
  await page.locator('div').filter({ hasText: /^0:012:59$/ }).getByRole('slider').fill('89');
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(2).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).first().click();
  await page.getByRole('button', { name: 'ВЫХОД' }).click();
  await page.getByText('БЕСКОНЕЧНЫЙ РЕЖИМ').click();
  await page.locator('body').press('ArrowLeft');
  await page.locator('body').press('ArrowLeft');
  await page.locator('body').press('ArrowLeft');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowLeft');
  await page.locator('body').press('ArrowRight');
  await page.getByRole('button', { name: 'ВЫХОД' }).click();
  await page.locator('#button3').click();
  await page.locator('body').press('ArrowLeft');
  await page.locator('body').press('ArrowLeft');
  await page.locator('body').press('ArrowLeft');
  await page.locator('body').press('ArrowLeft');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowLeft');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.getByRole('button', { name: 'ВЫХОД' }).click();
  await page.locator('#button4').click();
  await page.locator('body').press('ArrowLeft');
  await page.locator('body').press('ArrowLeft');
  await page.locator('body').press('ArrowLeft');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowLeft');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowLeft');
  await page.locator('body').press('ArrowLeft');
  await page.locator('body').press('ArrowLeft');
  await page.locator('body').press('ArrowLeft');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.getByRole('button', { name: 'ВЫХОД' }).click();
  await page.locator('#button5').click();
  await page.locator('body').press('ArrowLeft');
  await page.locator('body').press('ArrowLeft');
  await page.locator('body').press('ArrowLeft');
  await page.locator('body').press('ArrowLeft');
  await page.locator('body').press('ArrowLeft');
  await page.locator('body').press('ArrowLeft');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowLeft');
  await page.locator('body').press('ArrowLeft');
  await page.getByRole('button', { name: 'ВЫХОД' }).click();
  await page.getByRole('button', { name: 'НАЗАД' }).click();
  await page.getByText('РЕЙТИНГ').click();
  await page.getByTestId('page-button-2').click();
  await page.getByTestId('page-button-3').click();
  await page.getByTestId('page-button-4').click();
  await page.getByTestId('page-button-5').click();
  await page.getByTestId('back-button').click();
  await page.getByText('МУЗЫКА').click();
  await page.getByRole('button', { name: '→' }).click();
  await page.getByRole('button', { name: '←' }).click();
  await page.locator('.music-volume-bar').click();
  await page.locator('.music-progress-bar').dblclick();
});